const multer = require("multer");
const commonConstants = require("../common/constants");

/**
 * Custom error handling middleware for Multer.
 * This middleware is designed to be placed after multer-related routes.
 * It specifically catches and handles errors generated by multer,
 * such as file size limits or file filter rejections.
 */
const limitFileSize = (err, req, res, next) => {
    // Check if the error is an instance of MulterError
    if (err instanceof multer.MulterError) {
        if (err.code === "LIMIT_FILE_SIZE") {
            return res.status(commonConstants.STATUS_CODE.BAD_REQUEST).json({
                success: false,
                message: commonConstants.ATTACHMENT.CREATE.LIMIT_FILE_SIZE,
            });
        }
        // Handle other potential multer errors here if needed
        return res.status(commonConstants.STATUS_CODE.BAD_REQUEST).json({ success: false, message: err.message });
    } else if (err) {
        // This handles custom errors, like the one from our fileFilter
        return res.status(commonConstants.STATUS_CODE.BAD_REQUEST).json({ success: false, message: err.message });
    }

    next();
};

module.exports = limitFileSize;

